r"""
This file was *autogenerated* from tcc.tex with sagetex.sty
version 2020/08/12 v3.5. It contains the contents of all the
sageexample environments from tcc.tex. You should be able to
doctest this file with "sage -t tcc_doctest.sage".

It is always safe to delete this file; it is not used in typesetting your
document.

Sage commandline, line 1477::

sage: t = 1+1
sage: for i in range(101): # multiline input example
....: t+=111
sage:   t103
sage: factor(x^2 + 2*x + 1)

"""
